### ISSUE TITLE
Tag can't show all the problems

### ISSUE THREAD

**Issue by xinzhige** [jdneo/vscode-leetcode#107]
For example, in the graph tag, it only shows 9 questions but leetcode has 21.

**Comment by jdneo** [comment]
@xinzhige The reason why the number of listed problems is not equal to that on the website is due to two reasons:

1. Some of the problems are locked problems, if you want to list them in the explorer, change the extension setting: `leetcode.showLocked` to `true`.
  > Note: Only premium account can show the locked problems
2. The problem tag information is fetched from the [cli plugin](https://github.com/skygragon/leetcode-cli-plugins/blob/master/plugins/company.js), for now, it only contains the problem information up to No.750.

**Comment by jdneo** [comment]
This is fixed in https://github.com/leetcode-tools/leetcode-cli/pull/16

Please note that so far the problem tags are manually maintained, so when LeetCode publishes new problem, the tag might now get updated in time. I'll keep an eye on it. Meanwhile, thinking about how to get it automatically in the CLI.
