### ISSUE TITLE
Feature request - Prompt to create/open workspace  for leetcode

### ISSUE THREAD

**Issue by yaohaizh** [jdneo/vscode-leetcode#130]
When open topic from this extension, it will open/create new file on the current workspace
1. This will pollute the current workspace and SCM.
2. Hard to maintain local leetcode code.  

Expected:
Prompt user for separate workspace to organize the code per language.

**Comment by jdneo** [comment]
@poppinlp This issue is a little bit related to your previous work: #149. Would you like to have a try?

Basically, we can provide a new setting to set the leetcode workspace path. By default, it's `~/.leetcode`. And prompt user to open that workspace if it's not opened when generating leetcode file.

**Comment by poppinlp** [comment]
OK. I'll check it out.
