### ISSUE TITLE
第一次选择默认语言之后，就没有跳出选择语言的hint了，必须手动在设置里改别的语言

### ISSUE THREAD

**Issue by pharazone** [jdneo/vscode-leetcode#140]
第一次选择默认语言之后，就没有跳出选择语言的hint了，必须手动在设置里改别的语言，请问怎么在hint里调出来选择语言的界面，而不是每次都要在设置改别的语言。

谢谢了。

**Comment by jdneo** [comment]
@pharazone This is related to https://github.com/jdneo/vscode-leetcode/issues/115

We will consider adding a command to switch the language. For now, as a workaround, you can remove the default language setting, which can be found in the VS Code preference page.

Closing it since we already have an issue to track this problem.
