### ISSUE TITLE
I could not find leetcode:test

### ISSUE THREAD

**Issue by karangoel16** [jdneo/vscode-leetcode#15]
If possible please add Test module in your plugin as well, this will be of real help.

**Comment by jdneo** [comment]
@karangoel16 Yes, actually I'm also thinking to add this.

The problem is about the experience.

My idea is: 
1. User writes test case into a txt
2. User triggers the test command
3. Extension asks user to select the test case file
4. Extension uploads the test case and shows the result

What do you think? Please feel free to provide your ideas.  😄

**Comment by karangoel16** [comment]
I like the idea, but as leetcode-cli works, we can make it work for user given test case.

**Comment by jdneo** [comment]
@karangoel16 Yes, that's actually what I'm saying. User can write their own test cases into a file, and we upload this file.
As long as the user know the format for test cases. 

I guess we are in consensus, right?

**Comment by jdneo** [comment]
@karangoel16 Sorry, just take a look at the cli usage. Do you mean besides the user writen test case, also provide the default test case as well?

**Comment by karangoel16** [comment]
leetcode test 378.kth-smallest-element-in-a-sorted-matrix.cpp -t '[[1,5,9],[10,11,13],[12,13,15]]\n8'

user can paste this '[[1,5,9],[10,11,13],[12,13,15]]\n8' in command section and following would run like it runs with the normal leetcode test scenario.

**Comment by jdneo** [comment]
Make sense, this will be more straightforward way for simpler cases.

Thanks for the feedback, I'll implement this feature these days.

**Comment by jdneo** [comment]
New version released. Please try it out 🎉
