### ISSUE TITLE
Could not fetch correct tag for output folder

### ISSUE THREAD

**Issue by wangjunwei87** [jdneo/vscode-leetcode#176]
vscode:
![image](https://user-images.githubusercontent.com/1625837/53649925-47d1fa00-3c7e-11e9-9bd7-d7a7a93e7d8e.png)

leetcode description:
![image](https://user-images.githubusercontent.com/1625837/53649963-620bd800-3c7e-11e9-991a-6ab1a9775b89.png)

leetcode problem link: https://leetcode.com/problems/insert-into-a-cyclic-sorted-list/

**Comment by jjeejj** [comment]
in `leetcode.outputFolder` config, i use together ${tag}, ${difficulty}, ${language}
`"leetcode.outputFolder": "./${difficulty}/${tag}/${language}"`

but outFolder,  Only ${difficulty} worked
![image](https://user-images.githubusercontent.com/15176971/57895036-20053200-787c-11e9-9335-ba99c606d94a.png)

**Comment by jdneo** [comment]
@jjeejj This PR is addressing your problem

**Comment by jdneo** [comment]
This is fixed in https://github.com/leetcode-tools/leetcode-cli/pull/16

Please note that so far the problem tags are manually maintained, so when LeetCode publishes new problem, the tag might now get updated in time. I'll keep an eye on it. Meanwhile, thinking about how to get it automatically in the CLI.
