### ISSUE TITLE
Session expired problem

### ISSUE THREAD

**Issue by opjlmi** [jdneo/vscode-leetcode#2]
Hi, here is the bug

If I login leetcode.com by vscode, and login on chrome same time.
It will show the session expired problem.

<img width="1023" alt="2018-02-20 3 44 58" src="https://user-images.githubusercontent.com/6351593/36412411-09ed6d32-1655-11e8-8f3f-7e0cb4044fcc.png">

**Comment by jdneo** [comment]
Hi @opjlmi .

Thank you for trying this extension. What you have said is right and I can repro this on my side. But unfortunately, this issue cannot be fixed by the extension for now. Because the LeetCode only allow one active session per account. You can try using two browsers, (or one in common mode, one in incognito mode) both sign in with the same account, you will find as long as one browser signed in, the other will be signed out automatically(after refresh the web page).
