### ISSUE TITLE
Let font size of problem describe file equal to editor.fontSize not workbench font size.

### ISSUE THREAD

**Issue by roachsinai** [jdneo/vscode-leetcode#246]
## 🚀 Feature Proposal

Let font size of problem describe file equal to editor.fontSize not workbench font size.

## Motivation

The font size of problem describe file is to small.

![image](https://user-images.githubusercontent.com/9500049/55278280-0b5cf100-5345-11e9-9dc5-6c6a747ba361.png)

As it opening in editor section why the font size not equal editor font size?

![image](https://user-images.githubusercontent.com/9500049/55278288-4101da00-5345-11e9-879b-a9bf13533dd6.png)

**Comment by Vigilans** [comment]
The preview, solution and result webview will use built-in markdown engine's css file to render. So the best choice would be to use `markdown.preview.fontSize`.

However, I tested on my vscode and found that the setting wouldn't change the font size in the webview. It is because that I didn't ship the extra contribution logic from the original extension. I will work on this lately.

**Comment by roachsinai** [comment]
Thanks!

**Comment by Vigilans** [comment]
14.0 is now updated.

**Comment by roachsinai** [comment]
Seems the font of markdown still smaller than editor font size.

![image](https://user-images.githubusercontent.com/9500049/56560308-a2306c80-65d6-11e9-97f1-4e43e6858524.png)

**Comment by jdneo** [comment]
@roachsinai Did you update the setting: `markdown.preview.fontSize`?

**Comment by roachsinai** [comment]
@jdneo No, I didn't. Now, it workded, thanks!
