### ISSUE TITLE
装了node.js 还是会报leetcode.xxx 错误

### ISSUE THREAD

**Issue by seanxuu** [jdneo/vscode-leetcode#328]
## 🐛 Bug Report

装了node.js 还是会报leetcode.xxx 错误

## To Reproduce

我按照安装文档里的要求装了vscode 1.33.1 和 node.js 10.15.3 ，但是仍然会出现leetcode.xxx错误，我仔细查看了PATH和leet设置里的node.js路径，确信都无误。看了之前的issue，发现装上leetcode 0.12.0版本就不会出现这个情况。但是又会经常出现 Failed to submit the solution. Please open the output channel for details. 这个错误。

## Your Environment

- *os*: win10
- *extension settings*:按照文档要求设定
- *nodejs version*: 10.15.3
- *vscode version*: 1.33.1
- *extension version*: 0.14.2

**Comment by jdneo** [comment]
If your path has `Node.js` executable, there is no need to set the setting `leetcode.nodePath`. I think your problem is very similar to this one: https://github.com/jdneo/vscode-leetcode/issues/322#issuecomment-492614709

Please do remember that the path environment variable won't be automatically updated in the same session. You need to close the VS Code entirely and restart it from a new session.

**Comment by seanxuu** [comment]
“set leetcode.nodePath to its default value, which is node” helps me.
