### ISSUE TITLE
是否可以在title 上添加 难度提醒

### ISSUE THREAD

**Issue by lwjcjmx123** [jdneo/vscode-leetcode#333]
## 🚀 Feature Proposal

我目前是按照难度来刷题的。虽然有那个难度的分类，但是如果我想针对某些tag 比如动态规划来刷题的时候，我不能一眼看出来哪些是简单难度的。

## Motivation

希望title 能显示成这样 
[1] 两数之和  easy/简单/e
[2] 两数相加 medium/中等/m

## Contribution

如果觉得这个提议可行的话，我可以提交一个pr

**Comment by jdneo** [comment]
Hi @lwjcjmx123, 

Good to know you are willing to contribute. I think we have a duplicated issue here: https://github.com/jdneo/vscode-leetcode/issues/192. So let's just close this one and discuss the implementation details in that issue.

Instead of appending `easy/简单/e` at the end of the node. I prefer to use different colors to represent the different level. Just as the LeetCode website does:

![image](https://user-images.githubusercontent.com/6193897/58537974-b3e4df80-8226-11e9-975f-4b2b7af54289.png)

I'm not sure if it is feasible by the VS Code API (seems not). Another option is to use tooltips to hint the difficulty. Let's discuss them in #192 further.

Thanks.
