### ISSUE TITLE
在VS code按照leetcode使用问题

### ISSUE THREAD

**Issue by zhouhangzooo** [jdneo/vscode-leetcode#354]
在vsocde中登录leetcode后，可以看到很多题目，点击Submit | Test中的Test提交代码，会弹出结果界面（submission）；那么请问：如果我新增自己的题目（不是后台返回的题目数据），能不能使用这个Test功能呢？

![1561358445(1)](https://user-images.githubusercontent.com/37395573/59996869-19918380-968e-11e9-9818-376dc7f84b6c.jpg)

**Comment by jdneo** [comment]
Could you explain more about `自己的题目`?

**Comment by zhouhangzooo** [comment]
就是说不是leetcode直接返回的，是我自己创建的数据，包括题目示例，然后同样显示在vscode左侧栏中，请问能不能使用test功能呢？

**Comment by zhouhangzooo** [comment]
也就是说我不用leetcode的题目，但是想使用那个得到测评结果的功能。

**Comment by jdneo** [comment]
Assume that you want to debug your program in VS Code. If that is the case, it depends on what language you are using. VS Code has a lot of different extensions for different languages.

Take Java as an example: https://zhuanlan.zhihu.com/p/62521108.

You can find documents for other languages here: https://code.visualstudio.com/docs/nodejs/working-with-javascript

Since this is not an issue with the extension itself. I'm closing it for now.
