### ISSUE TITLE
LeetCode CN premium problem mismatch

### ISSUE THREAD

**Issue by liuyaf** [jdneo/vscode-leetcode#445]
![image](https://user-images.githubusercontent.com/17627746/66101787-16a40a00-e57e-11e9-808a-31cd0fc8d138.png)
如图，选择的题目是1057校园自行车，但是显示的题目是1012 至少有一位重复的数字。
![image](https://user-images.githubusercontent.com/17627746/66101907-85816300-e57e-11e9-8701-7e0e02ee3205.png)
实际提交也为1012。

**Comment by taoweicn** [comment]
+1
Wrong from 742
![image](https://user-images.githubusercontent.com/25795549/66248235-4a865780-e757-11e9-9faa-a9cda99e5827.png)

**Comment by jdneo** [comment]
Hi @all,

I cannot verify this issue since I do not have a premium account. But I find a potential problem. Could you please try to update the lib according to this PR: https://github.com/leetcode-tools/leetcode-cli/pull/28. And have a try to see if the problem still occurs? 

You can manually modify the file at: $home/.vscode/extensions/shengchen.vscode-leetcode-0.15.5/node_modules/vsc-leetcode-cli/*⁩ just the same as the [PR](https://github.com/leetcode-tools/leetcode-cli/pull/28) I referenced above.

**Comment by taoweicn** [comment]
Hi @jdneo, this issue was solved after following your guidance, but still #409 and #448.

**Comment by taoweicn** [comment]
@liuyaf Do you have the same [issue](https://github.com/jdneo/vscode-leetcode/issues/448) as me?

**Comment by taoweicn** [comment]
@jdneo Maybe the PR is defective, after applying the PR, I can not fetch any problems in `leetcode.com` though normal in `leetcode-cn.com`.

**Comment by EmiyaYang** [comment]
Hope this issue to be resolved in the next version.

**Comment by xaviercho** [comment]
Hey Guys, has this been properly resolved?
I'm still being forwarded to subscribe even though I have premium trying to access the exclusive problems on LC

https://support.leetcode.com/hc/en-us/community/posts/360034875813-Can-t-access-locked-problems-despite-having-paid-for-annual-subscription?page=1#community_comment_360009650093
