### ISSUE TITLE
Cannot using `Test` in LeetCode endpoint

### ISSUE THREAD

**Issue by moveingsun** [jdneo/vscode-leetcode#447]
## 🐛 Bug Report

Since this afternoon, when click test button, it hangs and no result were returned, while at the same time submit button works fine.

**Comment by ramezray** [comment]
Yes I'm experiencing same issue, only submit works, test does not.

**Comment by jdneo** [comment]
This is because LeetCode updated the API usage, so the CLI part is broken.

Before I release the fix, you can manually modify the file at: `$home/.vscode/extensions/shengchen.vscode-leetcode-0.15.5/node_modules/vsc-leetcode-cli/*⁩` just the same as the [PR](https://github.com/leetcode-tools/leetcode-cli/pull/27) I referenced above.

**Comment by ramezray** [comment]
Thanks @jdneo for your awesome work. Are you looking for someone to review or you still working on it?

**Comment by ramezray** [comment]
I was able to fix it manually, thanks a lot.
