### ISSUE TITLE
Does it support "Remember Me"

### ISSUE THREAD

**Issue by codyi96** [jdneo/vscode-leetcode#463]
It is too cumbersome to enter the account&password every time I log in.🥵

**Comment by jdneo** [comment]
This is a restriction from the LeetCode website.

If the same account is logged in from two different endppoint(e.g. extension & browser). The previous one will be kick-off.

But since now we support Third-Party login, this problem should be somehow mitigated.

Please have a try.

I will close this issue. But please feel free to let me know if you have any more questions.

Thanks,
