### ISSUE TITLE
Get the Tree view info

### ISSUE THREAD

**Issue by friendfish** [jdneo/vscode-leetcode#480]
Before you submit an question we recommend you to check out the [DOCUMENT](https://github.com/jdneo/vscode-leetcode/blob/master/README.md) first.

You can also find more information in:
- [TROUBLESHOOTING](https://github.com/jdneo/vscode-leetcode/wiki/Troubleshooting)
- [FAQ](https://github.com/jdneo/vscode-leetcode/wiki/FAQ)

## 💬 Questions and Help

Please outline the questions.
With vscode-leetcode plugin, I can get all the problem list in Leetcode websit, cause of vscode-leetcode wrapped the info and write in log.
forthermore, I want get more info by text format, for example the tag, comapny etc.
Use that info, I will management the schedule for work-out on the problem.

Could anyone do me a favor?
thanks~

**Comment by jdneo** [comment]
@friendfish The extension is just parsing the output from the [LeetCode CLI](https://github.com/leetcode-tools/leetcode-cli).

I'm not sure if LeetCode has such kind of API for this. As far as I know, you need to write your own crawler to get such information.

Closing since it's out of the extension's scope. But please feel free to share your thoughts if you have any.

Thanks.
