### ISSUE TITLE
Beautify console version output format

### ISSUE THREAD

**Issue by hardboydu** [jdneo/vscode-leetcode#498]
## 🚀 Feature Proposal

Beautify console version output format

## Motivation

Looks comfortable

## Contribution

```js
problem.desc = problem.desc.split("<strong>").join("\u001b\u005b1m")
problem.desc = problem.desc.split("</strong>").join("\u001b\u005b0m")
```

![捕获](https://user-images.githubusercontent.com/4214337/71495690-32236600-288a-11ea-902c-250779995405.PNG)

**Comment by jdneo** [comment]
@hardboydu I think this should be an issue related with the [CLI](https://github.com/leetcode-tools/leetcode-cli). Please create the issue there, or contribute a PR if you want. 😄 

Closing this issue since it's not a extension side issue. But feel free to let me know if I misunderstand anything.

Thanks.
