### ISSUE TITLE
The test cases cannot have quotes (")

### ISSUE THREAD

**Issue by Licheng-Xu** [jdneo/vscode-leetcode#60]
尝试使用 "00000" 或者 \"00000\" 都不行

**Comment by jdneo** [comment]
Hi @Licheng-Xu 

可以提供一下题号吗？

**Comment by Licheng-Xu** [comment]
不好意思，这几天忙着其他事情了。

题号：[13]
[Roman to Integer](https://leetcode.com/problems/roman-to-integer/description/)

选择直接输入测试样例，输入 "LVIII"，之后返回了

> Input data:
> LVIII
> 
> Actual
>   × Runtime Error
>   × runtime: N/A
>   × answer: 
>   × stdout: ''
>   × error: terminate called after throwing an instance of 'std::logic_error'
>   what():  basic_string::_M_construct null not valid
> 
> Expected
>   × Runtime Error
>   × runtime: N/A
>   × answer: 
>   × stdout: ''
>   × error: Line 68: ValueError: No JSON object could be decoded

**Comment by jdneo** [comment]
@Licheng-Xu It looks like a bug. Thank you for the feedback. 👍

**Comment by LiuLiC** [comment]
Hi @jdneo , looks like the bug happened because in test.ts: when we get the test string, we replace /" and /g with "", which drops quotes. Thus in leetcode, it can't recognize the input as a string.

**Comment by jdneo** [comment]
@LiuLiC Yeah, I know that. Because I remember that there is a problem is we do not do the replacement.

Not quite sure how the current status is. PR is welcome if you are willing to fix this. 😄

**Comment by jdneo** [comment]
Fixed in #111.

Will get released in `0.10.2`

**Comment by jdneo** [comment]
Hmm...

Actually, this bug is not well fixed in #111. I did some experiments on different platforms and found that the test string needs to be parsed in different ways:

### Bash (Mac)
`'"XX"'`

### CMD (Windows)
`"\"XX\""`

### PowerShell (Windows)
`'\"XX\"'`

I have no Linux machine to verify, but guess the behavior should be similar with that in `Bash`.

So I created another PR: #113, to fix it.

**Comment by jdneo** [comment]
@all 0.10.2 has been released with this fix.
